CREATE DATABASE  IF NOT EXISTS `test`;

USE `test`;

CREATE TABLE IF NOT EXISTS `mq_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;